version: '3.9'

services:
  db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
  api:
    container_name: mks-backend
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn start:dev'
    depends_on:
      - db

